# Generated by Django 2.2.1 on 2019-05-11 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(blank=True, default='user_profile/default_profile.png', upload_to='user_profile', verbose_name='Profile')),
                ('about', models.TextField(blank=True, max_length=512)),
                ('registration_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='common_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
