# Generated by Django 2.2.1 on 2019-05-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='about',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
