# Generated by Django 2.2.1 on 2019-05-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_user', '0002_auto_20190503_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='profile',
            field=models.ImageField(default='user_profile/default_profile.png', upload_to='user_profile', verbose_name='Profile'),
        ),
    ]
