# Generated by Django 2.2.1 on 2019-05-14 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_user', '0002_auto_20190514_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonuser',
            name='friend_request_receive',
        ),
        migrations.RemoveField(
            model_name='commonuser',
            name='friend_request_send',
        ),
        migrations.RemoveField(
            model_name='commonuser',
            name='friends',
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='common_user.CommonUser')),
                ('users', models.ManyToManyField(to='common_user.CommonUser')),
            ],
        ),
    ]
