# Generated by Django 2.2.1 on 2019-05-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_user', '0003_auto_20190504_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='profile',
            field=models.ImageField(blank=True, default='user_profile/default_profile.png', upload_to='user_profile', verbose_name='Profile'),
        ),
    ]
