# Generated by Django 2.2.1 on 2019-05-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_user', '0004_commonuser_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='followers',
            field=models.ManyToManyField(related_name='_commonuser_followers_+', to='common_user.CommonUser'),
        ),
    ]
