# Generated by Django 2.2.1 on 2019-05-04 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_user', '0005_auto_20190505_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
