# Generated by Django 2.2.1 on 2019-05-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_user', '0006_auto_20190514_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonuser',
            name='friend_request_received',
            field=models.ManyToManyField(related_name='received', to='common_user.CommonUser'),
        ),
        migrations.AddField(
            model_name='commonuser',
            name='friend_request_sent',
            field=models.ManyToManyField(related_name='sent', to='common_user.CommonUser'),
        ),
        migrations.AddField(
            model_name='commonuser',
            name='friends',
            field=models.ManyToManyField(related_name='_commonuser_friends_+', to='common_user.CommonUser'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
