# Generated by Django 2.2.1 on 2019-05-11 08:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common_user', '0001_initial'),
        ('my_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('create_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_author', to='common_user.CommonUser', to_field='user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_to_post', to='my_post.Post')),
            ],
            options={
                'ordering': ['-create_data'],
            },
        ),
    ]
