# Generated by Django 2.2.1 on 2019-05-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['create_data']},
        ),
    ]
