# Generated by Django 2.2.1 on 2019-05-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_post', '0002_auto_20190506_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_data']},
        ),
    ]
