# Generated by Django 2.2.1 on 2019-05-18 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_user', '0007_auto_20190516_1339'),
        ('my_post', '0002_post_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='to_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_in_user_page', to='common_user.CommonUser'),
        ),
    ]
