# Generated by Django 2.2.1 on 2019-05-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_user', '0001_initial'),
        ('my_group', '0002_auto_20190511_1407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupAdministrators',
            new_name='GroupAdministrator',
        ),
    ]
